fav_movies/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("moviesapp/", include("moviesapp.urls")),
    path("", include("pages.urls")),
]

moviesapp/urls.py
from django.urls import path

from . import views

# Namespace
app_name = "moviesapp"

urlpatterns = [
    # "/moviesapp"
    path("", views.index, name="index"),
    path("<int:question_id>/", views.detail, name="detail"),
    path("<int:question_id>/results/", views.results, name="results"),
    path("<int:question_id>/favorite/", views.favorite, name="favorite"),
]

pages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # "/"
    path("", views.index, name="index")
]

moviesapp/models.py
import datetime

from django.db import models
from django.utils import timezone


# Create your database models here
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    likes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

pages/models.py
from django.db import models

# Create your models here.

moviesapp/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone

from .models import Choice, Question


# Create your views here.
# Getting movies
def index(request):
    latest_question_list = Question.objects.filter(
        pub_date__lte=timezone.now()
    ).order_by("-pub_date")[:10]
    context = {"latest_question_list": latest_question_list}
    # Loads templates
    return render(request, "moviesapp/index.html", context)


# Show movie
def detail(request, question_id):

    try:
        question = Question.objects.filter(pub_date__lte=timezone.now()).get(
            pk=question_id
        )
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, "moviesapp/detail.html", {"question": question})


# Show results
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "moviesapp/results.html", {"question": question})


# Add favorite movie/serie/etc
def favorite(request, question_id):
    # print("POST: " + request.POST['choice'])
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question form.
        return render(
            request,
            "moviesapp/detail.html",
            {"question": question, "error_message": "You didn't select a choice.",},
        )
    else:
        selected_choice.likes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("moviesapp:results", args=(question.id,)))

pages/views.py
from django.shortcuts import render


# Landing page
def index(request):
    return render(request, "pages/index.html")

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Favorite Movies {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    {% include 'partials/_navbar.html' %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 m-auto">
                {% block content %}

                {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

templates/moviesapp/detail.html
{% extends 'base.html' %}
{% block content %}
<a class="btn btn-secondary btn-sm mb-3" href="{% url 'moviesapp:index' %}">Back</a>
<h1 class="text-center mb-3">{{ question.question_text }}</h1>

{% if error_message %}
<p class="alert alert-danger">
	<strong>{{ error_message }}</strong>
</p>
{% endif %}

<form action="{% url 'moviesapp:favorite' question.id %}" method="post">
	{% csrf_token %}
	{% for choice in question.choice_set.all %}
		<div class="form-check">
			<input
				type="radio"
				name="choice"
				class="form-check-input"
				id="choice{{ forloop.counter }}"
				value="{{ choice.id }}"
			/>
			<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
		</div>
	{% endfor %}
	<input type="submit" value="Select" class="btn btn-success btn-lg btn-block mt-4" />
</form>
{% endblock %}

templates/moviesapp/index.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="text-center mb-3">
        Favorite Movies
    </h1>
    {% if latest_question_list %}
        {% for question in latest_question_list %}
            <div class="card mb-3">
              <div class="card-body">
                  <p class="lead">{{ question.question_text }}</p>
                  <a href="{% url 'moviesapp:detail' question.id %}" class="btn btn-primary btn-sm">
                      Choose
                  </a>
                  <a href="{% url 'moviesapp:results' question.id %}" class="btn btn-secondary btn-sm">
                      Results
                  </a>
              </div>
            </div>
        {% endfor %}
    {% else %}
        <p>No questions available</p>
    {% endif %}
{% endblock %}

templates/moviesapp/results.html
{% extends 'base.html' %}
{% block content %}
<h1 class="mb-5 text-center">{{ question.question_text }}</h1>

<ul class="list-group mb-5">
	{% for choice in question.choice_set.all %}
	<li class="list-group-item">
		{{ choice.choice_text }}  <span class="badge badge-success float-right">{{ choice.likes }} like{{ choice.likes | pluralize }}</span>
	</li>
	{% endfor %}
</ul>

<a class="btn btn-secondary" href="{% url 'moviesapp:index' %}">Back</a>
<a class="btn btn-dark" href="{% url 'moviesapp:detail' question.id %}">Select another</a>
{% endblock %}

templates/pages/index.html
{% extends 'base.html' %}
{% block content %}

<div class="card text-center">
  <div class="card-body">
    <h1>Favorite Movies</h1>
    <a class="btn btn-dark" href="{% url 'moviesapp:index' %}">
        Search and add movies</a>
  </div>
  </div>
{% endblock %}

templates/partials/_navbar.html
<nav class="navbar navbar-dark bg-primary mb-4">
	<div class="container">
		<a class="navbar-brand" href="/">Favorite Movies</a>
	</div>
</nav>